services:
  debian:
    image: debian:bookworm-slim
    platform: linux/x86_64
    container_name: debian
    privileged: true
    # security_opt:
    #   - seccomp:unconfined
    # cap_add:
    #   - SYS_PTRACE
    #   - SYS_ADMIN
    command: >
      /bin/sh -c '
        if [ ! -e ~/.initialized ]; then
          apt-get -y update &&
          apt-get -y upgrade &&

          groupadd -g 100 users -f &&
          useradd -g users -u 1001 5ky12hm &&

          apt-get -y install \
            zsh \
            git \
            curl \
            wget \
            xz-utils \
            binutils \
            file \
            procps \
            gcc \
            make \
            strace \
            python3 \
            python3-pip \
            python3-dev \
          &&
            
          apt-get -y install gdb qemu-user-static &&
          echo 0 > /proc/sys/kernel/yama/ptrace_scope &&

          # commented out: cannot print running info
          # ValueError: Argument 'count' should be greater than zero
          # curl -qsL "https://install.pwndbg.re" | sh -s -- -t pwndbg-gdb &&

          python3 -m pip install --break-system-packages --upgrade \
            pip \
            pwntools \
          &&

          touch ~/.initialized
        fi
        tail -F /dev/null
      '
    volumes:
      # - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ~:/home/5ky12hm
      - /mnt/share:/mnt/share
